# -*- coding: utf-8 -*-
"""henrietta_extra01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4vpA2QJbhADIw41zhoHCFcLNAUrDgT7
"""

import random
play_again = True                                                                 #Declares that the player wants to play a game
total = 0
won = 0
while play_again == True:                                                         #while the player wants to play the game the loop continues
  number = random.randint(0, 1000)                                                #Generates a random number between 0 and 1000
  correct = False                                                                 #assumes guess is not correct as initial form
  count = 0                                                                       #counts number of turns starts at 0
  guess = -1
  while correct == False and count < 10:
    guess = int(input("Guess the number between 0 and 1000."))
    if(guess < 0 or guess > 1000):
      print("When entering a number please make sure it is between 0 and 1000")
      guess = int(input("Guess the number between 0 and 1000."))
    if(guess > number):                                                           #checks if guess is higher than designated number
      print("Too High!")                                                          #Prints too high
    elif(guess < number):                                                         #checks if guess is lower than designated number
      print("Too Low!")                                                           #Prints too high
    else :                                                                        #If other two conditions were not met the guess must be correct
      print("Correct!")                                                           #Tell the player they are correct
      correct = True                                                              #Set correct to true
      won += 1
    count += 1
  if(correct == False):                                                           #If the player did not guess correctly in 10 turns
    print("Nice try you lose, the number was, ",number)                           #Print that the player was wrong and says the correct answer
  else :
    print("Great job!")
  again = input("Do you want to play again? Type y for yes, or n for no.")        #Checks if user wants to play agin
  if again == "y":
    play_again = True                                                             #Wants to play agin is true and the game will be played again
  else :
    play_again = False                                                            #Wants to play agin is False and the game will NOT be played again
  total += 1
  print("-----------------------------------------------------------------------")
  print()
  print()
  print("You have won, ",won," games out of ", total, "games.")
  print()
  print()
  print("-----------------------------------------------------------------------")