# -*- coding: utf-8 -*-
"""Sarah_Extra01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ri9-soXIxA6jjcnjMov_rjs0_xxnFL8
"""

import random
rand_int = random.randint(1,1000)
guess_range = range(1,1000)

guess = int(input("Guess the number between 1 and 1000: "))

remaining_chances = 9

while guess != rand_int and remaining_chances > 0:
    if guess < rand_int and guess in guess_range:
        print("Too low!")
        guess = int(input("Guess again: "))
        remaining_chances = remaining_chances - 1
    elif guess > rand_int and guess in guess_range:
        print("Too high!")
        guess = int(input("Guess again: "))
        remaining_chances = remaining_chances - 1
    elif guess not in guess_range:
        print("Out of range!")
        guess = int(input("Guess again: "))

if guess == rand_int:
    print("Correct! Congratulations :-) Would you like to play again?")
elif remaining_chances == 0:
    print("You lose :-( Would you like to play again?)")